sudo: required
services:
  - docker

before_install:
  - docker build -t william2772/fib-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true william2772/fib-client npm test

after_success:
  - docker build -t william2772/fib-client ./client
  - docker build -t william2772/fib-nginx ./nginx
  - docker build -t william2772/fib-api ./api
  - docker build -t william2772/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  - docker push william2772/fib-client
  - docker push william2772/fib-nginx
  - docker push william2772/fib-api
  - docker push william2772/fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container-fib-calulator-app
  env: MultiContainerFibCalulatorApp-env
  bucket_name: elasticbeanstalk-us-east-2-571983945258
  bucket_path: multi-container-fib-calulator-app
  on:
    branch: master
  access_key_id: $FIB_AWS_ACCESS_KEY
  secret_access_key: $FIB_SECRET_ACCESS_KEY